### ISSUE TITLE
When performing e2e test, POD and SA are created in arbitrary namespace, not in kis

### ISSUE THREAD

**Issue by hookak** [tmax-cloud/kubevirt-image-service#39]
When performing  e2e test, operator-sdk create manifest file as follows

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-image-service
  namespace: kis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubevirt-image-service
rules:
- apiGroups:
...
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-image-service
subjects:
- kind: ServiceAccount
  name: kubevirt-image-service
  namespace: kis
roleRef:
  kind: ClusterRole
  name: kubevirt-image-service
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kubevirt-image-service
  namespace: kis
spec:
  replicas: 3
...
```

The service account and deployment must be created in the kis namespace, but operator-sdk creates them in an arbitrary namespace. Clusterrolebindng binds service account and role in kis namespace. So, operators created in arbitrary namespaces do not have an appropriate role.

```
user@ubuntu26:~/repo/kubevirt-image-service$ kubectl get sa -A
NAMESPACE                                       NAME                                 SECRETS   AGE
osdk-e2e-388def45-86c5-48c8-a2f9-dda757fd096c   default                              1         42s
osdk-e2e-388def45-86c5-48c8-a2f9-dda757fd096c   kubevirt-image-service               1         42s
...

user@ubuntu26:~/repo/kubevirt-image-service$ kubectl get po -A
NAMESPACE                                       NAME                                                 READY   STATUS             RESTARTS   AGE
osdk-e2e-388def45-86c5-48c8-a2f9-dda757fd096c   kubevirt-image-service-b474cf4c9-5g5v7               0/1     Error              3          73s
osdk-e2e-388def45-86c5-48c8-a2f9-dda757fd096c   kubevirt-image-service-b474cf4c9-9ghnq               0/1     CrashLoopBackOff   2          73s
osdk-e2e-388def45-86c5-48c8-a2f9-dda757fd096c   kubevirt-image-service-b474cf4c9-s425b               0/1     CrashLoopBackOff   2          73s
...
```

When performing e2e test, it is recommended to add '--operator-namespace' flag.
